# -*- coding: utf-8 -*-
"""Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DwEdOfQTLsNBk5rGdUzh9dVjT7myMkdB
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import kagglehub

# Load dataset from Kaggle
path = kagglehub.dataset_download("spscientist/students-performance-in-exams")
df = pd.read_csv(path + "/StudentsPerformance.csv")

# Clean column names
df.columns = df.columns.str.replace(" ", "_")

# Subject-wise analysis
subjects = ["math_score", "reading_score", "writing_score"]
avg_scores = df[subjects].mean()

# Strength & Weakness
print("Strength:", avg_scores.idxmax())
print("Weakness:", avg_scores.idxmin())

# ----- Dashboard -----
plt.figure(figsize=(12,4))

plt.subplot(1,3,1)
avg_scores.plot(kind="bar", color="cornflowerblue")
plt.title("Average Scores")
plt.ylabel("Marks")

plt.subplot(1,3,2)
sns.boxplot(data=df[subjects])
plt.title("Marks Distribution")

plt.subplot(1,3,3)
plt.pie(avg_scores, labels=subjects, autopct="%1.1f%%", startangle=90)
plt.title("Subject-wise Performance Share")

plt.tight_layout()
plt.show()